version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    image: hyper-vibeshopping
    container_name: team09-hyper-vibe-shopping
    ports:
      - "1900:8000"

networks:
  ai4thai_net:
    external: true

volumes:
  example-root:
    external: true
  example-data:
    external: true
