version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    image: hyper-vibeshopping
    container_name: team09-hyper-vibe-shopping
    ports:
      - "1900:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

networks:
  ai4thai_net:
    external: true

volumes:
  example-root:
    external: true
  example-data:
    external: true
